chrippa/livestreamer

src/livestreamer/plugins/tga.py
I have add tga.plu.cn support.
Tga.plu.cn is a China Tencent Game Arena live platform.
=> Plugins - tag.plu.cn - support

src/livestreamer/plugins/tga.py
fixed nothing repeat on the version of  python less that 2.7.6.
=> supports version of python less that 2.7.6

src/livestreamer/plugins/nos.py
Added plugin for NOS (Nederlandse Omroep Stichting) (http://www.nos.nl)
=> Added plugin: NOS (Nederlandse Omroep Stichting)

src/livestreamer/plugins/wattv.py
Added plugin for wat.tv per request #650
=> Added plugin: wat.tv

src/livestreamer/plugins/tga.py
Hi,
1. tga website has renamed longzhu.tv
2. Add flash stream
=> Update tga plugin

docs/plugin_matrix.rst, src/livestreamer/plugins/tvplayer.py
=> Added plugin for tvplayer.com

docs/plugin_matrix.rst, src/livestreamer/plugins/gaminglive.py
Hi,
Apart from vod support, I've also changed regex to support URLs without `www` and fixed typo in docs.
=> plugins.gaminglive: Add VOD support.

docs/plugin_matrix.rst, src/livestreamer/plugins/ssh101.py
Here it's a plugin to play Live content from http://ssh101.com/. This service has also VOD content, but it is currently broken (flash player show an error message). I send an email about this issue, but without any answers. Personally I only use live streaming on this service, so for me this is not an issue.
=> Plugin to play Live content from SSH101

src/livestreamer/plugins/tvcatchup.py
The TVCatchup.com website layout changed and the method to find the stream URLs needed to be updated.
=> Fix for the tvcatchup.com plugin

docs/plugin_matrix.rst, src/livestreamer/plugins/meerkat.py
Hello,
This is a plugin for Meerkat, quite straightforward.
Thanks
=> Add Meerkat plugin

src/livestreamer/plugins/azubutv.py
Hi all:
Azubutv website has released from yesterday, so, the azubutv plugin is not working. 
Now, I fix it that it gets live status of this channel from  api server.
=> update azubutv plugin

docs/plugin_matrix.rst, src/livestreamer/plugins/ruv.py
Hello,
I've created a plugin that works with Rúv ( [http://www.ruv.is](http://www.ruv.is) ). The plugin work both for the livestream (television and radio) and the VOD service called Sarpurinn. The streams can only be viewed in Iceland.
Hannes
=> Plugin for Rúv - The Icelandic national television

docs/plugin_matrix.rst, src/livestreamer/plugins/periscope.py
=> Add VOD/replay support for periscope.tv

src/livestreamer/plugins/artetv.py
=> plugins.artetv: Update json regex

src/livestreamer/plugins/azubutv.py
I find new azubu api for streaming, but now Livestream get these params that it's parsing the Azubu website, it's always unstable.
=> Azubu support

src/livestreamer/plugins/douyutv.py
Fix for douyutv.com
fix for #809
=> Updated douyutv.com plugin

docs/plugin_matrix.rst, src/livestreamer/plugins/livecodingtv.py
Added support for streaming channels from https://livecoding.tv/
I didnt see any docs for plugin development so feel free to let me know if I'm missing anything. Theres no quality options on the site so I just added a "live" option.
=> Added support for livecoding.tv

src/livestreamer/plugins/npo.py
This fixes #921 since npo implemented a token changer Why I have no clue but this should fix it
=> NPO token fix

src/livestreamer/plugins/streamupcom.py
streamup.com: Fix for API change
=> plugins.streamupcom: Update for API change

src/livestreamer/plugins/servustv.py
Plugin for the FreeTV channel ServusTV. (& thanks for your great work!)
=> New Plugin: ServusTV

src/livestreamer/plugins/streamupcom.py
If the stream is down, the stream url gives a 404. How should I handle the error?
=> Update the streamup.com plugin

src/livestreamer/plugins/ustreamtv.py
I made the validation work but I doubt it's correct, and it looks like something is parsing wrong, so the real problem is likely deeper and beyond my expertise.
=> Possible fix for ustream

docs/plugin_matrix.rst
=> docs/plugin_matrix: removed needless characters

src/livestreamer/plugins/douyutv.py
Use douyutv new api for android with HLS stream feature.
=> plugins.douyutv: Use new api.

src/livestreamer/plugins/picarto.py
=> plugins.picarto: Update for API and URL change
