src/livestreamer_cli/argparser.py, src/livestreamer_cli/main.py, src/livestreamer_cli/utils/http_server.py
Add an option to the CLI name --player-external-http, to start an HTTP
server like --player-continuous-http, but without starting a
corresponding player, and streaming to all available interfaces instead
of just the loopback.
This can be useful to stream to devices like smartphones or streaming
boxes, while making use of the better compatibility and performance of
livestreamer.
An accompanying --player-external-http-port option was added to allow
people behind firewalls to add their exceptions only once.
When starting livestreamer in this mode, URLs for the server will be
printed instead of a player being started. Those are detected based
on the IPv4 addresses returned by calling
socket.getaddrinfo(socket.gethostname(), ...), which will work for sure
on UNIX platforms, and should on …
=> cli: add option to server streams externally without a player

src/livestreamer/plugins/disney_de.py
Added plug-in: Disney and Disney Channel Germany per request #679
=> Added plugin: Disney and Disney Channel Germany

src/livestreamer/plugins/connectcast.py
closes #718 #606 
I don't know about vods, but it seems connectcast changed their streaming method to using an `f4m` manifest without a direct rtmp link. This PR allows streaming to work with `http://connectcast.tv/{channel_name}`.
=> Fix connectcast.tv livestreaming

src/livestreamer/plugins/veetle.py
closes #752.
current veetle "short url" returns a http 301 moved permanently response; resolve_url the needed url before matching/etc.
=> plugins.veetle: simple redirect fix

src/livestreamer/plugins/rtve.py
closes #649.
rtve.es has new urls for their streams and redirects to them via 301 when visiting the old url.
added regex for the new urls.
=> plugins.rtve: new url regex, old now redirects

docs/plugin_matrix.rst, src/livestreamer/plugins/tvcatchup.py
A new plugin to support www.tvcatchup.com streams - might be geo-restricted to the UK.
=> TVCatchup.com Plugin

docs/plugin_matrix.rst, src/livestreamer/plugins/itvplayer.py
A new plugin that plays content from ITV Player.
=> Plugin to play VOD and Live content from ITVPlayer

src/livestreamer_cli/main.py
The user_subscriptions scope is required to watch streams that need a subscription
Failure to do so will result in the following error:
Failed to authenticate, the access token is invalid or missing required scope
=> Add user_subscriptions scope to Twitch OAuth request

src/livestreamer/plugins/connectcast.py
Fixed TypeError by changing res.content to str type
=> Fixed connectcast.tv TypeError

src/livestreamer/plugins/gaminglive.py
For some reason we have to create the RTMPStream with "live" = True for
VODs too or they won't play. I also changed the name of the VOD quality
from the video title to "source". It made more sense to me.
=> plugins.gaminglive: VOD support fixed

src/livestreamer/plugins/crunchyroll.py
The PS3 API tokens seem to have changed. Modified the auth token and headers we send to fix that. See this [commit](https://github.com/MattRK/Crunchyroll.bundle/commit/17b5fe83a0982cf5c49a8b8de5bfa27012fe6832) for the related change on the flex plugin.
Fixes #864
*Note:* not sure if I should be sending this pull request against master, since it's pretty urgent. Let me know in any case if you need me to change it.
=> Fix crunchyroll api auth

src/livestreamer/plugins/vaughnlive.py
fixes  #897
vaughnlive changed a delimiter in their api, updated the plugin accordingly.
tested with all three sites supported by the plugin (vaugnlive.tv, breakers.tv, vapers.tv)
=> fix vaughnlive plugin #897

docs/plugin_matrix.rst, src/livestreamer/plugins/bliptv.py
Hi,
I added this plugin for personal use but decided it might be useful for everyone.
=> Added plugin for blip.tv VOD

docs/plugin_matrix.rst, src/livestreamer/plugins/expressen.py
Hi, had a go at a plugin for Expressen.
Some rationale:
The HDS manifest is only linked on VODs, on live streams the tag exists but is a void element => still look for it should it change in the future. VODs have one RTMP stream linked, which never seems to work (no data received) => skip RTMP when not live (live streams do have multiple working RTMP streams). The mobile URLs have one RTSP stream, the rest are HLS master playlists => only look for scheme=http, file=m3u8, skip rest. The mobile URLs are sometimes identical, hence the set.
I wasn't sure how the RTMP streams should be named should the bitrate be missing since then there would be zero metadata. Should additional RTMP parameters be added? e.g. live, pageUrl
=> Plugin for Expressen

src/livestreamer/plugins/tvcatchup.py
Fixed support for channels with not adaptive playlist.
Set the User-Agent header to fix a possible 403 error.
=> TVCatchup.com bugfix

src/livestreamer/plugins/crunchyroll.py, src/livestreamer_cli/argparser.py, src/livestreamer_cli/main.py
Added support for locale selection on the Crunchyroll plugin through the `crunchyroll-locale` command line option.
Closes #364.
=> plugins.crunchyroll: added support for locale selection

src/livestreamer/plugins/goodgame.py
URL can be without trailing slash. Example: http://goodgame.ru/channel/test
In that case livestreamer will fail to found plugin and that is confusing.
=> GoodGame URL parse fix

src/livestreamer/plugins/nrk.py
This change makes it possible to use https urls on nrk.no. I'm not particularly skilled at python, so hopefully I did things correctly.
=> Allow https urls for nrk.no.

src/livestreamer_cli/utils/http_server.py
Working on a project of my own that uses Livestreamer, I stumbled upon [an issue](https://github.com/best-coloc-ever/twitch-cast/issues/10) while using the `--player-external-http` option
Basically, if a socket sends an HTTP request and closes before Livestreamer's HTTP server sends the response, consequent calls to `send` on the socket will send a `SIGPIPE` to Livestreamer's process which will raise a `socket.error` exception that was currently not caught.
[Possible environment to reproduce](https://github.com/best-coloc-ever/twitch-cast/blob/master/streamer%2FDockerfile)
For example, running this command:
```sh
livestreamer twitch.tv/dotamajor best \
--player-external-http \
--player-external-http-port 12345
```
Followed by this little script:
```sh
while true; do 
curl …
```
=> Fix crashes on HTTPServer's SIGPIPE

src/livestreamer/plugins/media_ccc_de.py
* the media.ccc.de url scheme was changed after upgrading to a new frontend
* streaming.media.ccc.de supports also https
=> plugin: added media_ccc_de api and protocol changes

src/livestreamer/plugins/azubutv.py
This prevents an error with traceback and instead just prints "No streams
found" like it should if the stream in question is not live. Fixes #1083.
=> azubutv: set video_player to None if stream is offline
